import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:3001';
const empty={codigo:'',nome_completo:'',cpf_cnpj:'',nascimento:'',tipo_cliente:'Pessoa Física',telefone:'',whatsapp:'',email:'',cep:'',endereco:'',numero:'',complemento:'',bairro:'',cidade:'',estado:'',origem_cadastro:'',responsavel:'',status:'ativo',categoria_cac:'',cr_numero:'',cr_emissao:'',cr_validade:'',cr_situacao:'',cr_orgao:'',observacoes:''};
function F({label,name,type='text',required=false,form,setForm}){return <label><span>{label}{required?' *':''}</span><input type={type} value={form[name]||''} required={required} onChange={e=>setForm(prev=>({...prev,[name]:e.target.value}))}/></label>}

function gerarDeclaracao(detail){
  const nome=detail.nome_completo||detail.razao_social||detail.nome||'';
  const doc=detail.cpf_cnpj||'';
  const cidade=detail.cidade||'';
  const estado=detail.estado||'';
  const hoje=new Date().toLocaleDateString('pt-BR');
  const endereco=[detail.endereco,detail.numero,detail.complemento,detail.bairro].filter(Boolean).join(', ');
  const w=window.open('','_blank','width=900,height=900');
  if(!w)return;
  w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Declaração de Inexistência de Inquérito</title><style>body{font-family:Arial,sans-serif;color:#17212b;margin:0;padding:55px;line-height:1.6}header{text-align:center;border-bottom:3px solid #1769aa;padding-bottom:18px;margin-bottom:45px}h1{font-size:22px;margin:0;color:#1769aa}h2{font-size:17px;text-align:center;margin:35px 0}.dados{border:1px solid #d9e1e7;border-radius:8px;padding:18px;margin:25px 0}.dados p{margin:5px 0}.assinaturas{display:grid;grid-template-columns:1fr 1fr;gap:60px;margin-top:90px;text-align:center}.linha{border-top:1px solid #333;padding-top:8px}.rodape{margin-top:60px;font-size:12px;color:#667085}@media print{body{padding:35px}}</style></head><body>');
  w.document.write('<header><h1>CAC GESTÃO</h1><div>DECLARAÇÃO DE INEXISTÊNCIA DE INQUÉRITO</div></header>');
  w.document.write('<h2>DECLARAÇÃO</h2>');
  w.document.write('<p>Declara-se, para os devidos fins, que, após consulta aos registros internos disponíveis nesta data, <strong>não foi localizado registro de inquérito</strong> em nome do cliente abaixo identificado.</p>');
  w.document.write('<div class="dados"><p><strong>Nome / Razão Social:</strong> '+nome+'</p><p><strong>CPF/CNPJ:</strong> '+doc+'</p>'+ (detail.codigo?'<p><strong>Código:</strong> '+detail.codigo+'</p>':'') + (endereco?'<p><strong>Endereço:</strong> '+endereco+'</p>':'') + (cidade?'<p><strong>Município/UF:</strong> '+cidade+(estado?' - '+estado:'')+'</p>':'') + '</div>');
  w.document.write('<p>A presente declaração é emitida com base exclusivamente nos registros internos consultados no momento de sua emissão, para os fins a que se destinar.</p>');
  w.document.write('<p>'+cidade+(cidade?', ':'')+estado+', '+hoje+'.</p>');
  w.document.write('<div class="assinaturas"><div class="linha">Responsável pela emissão</div><div class="linha">Assinatura / Carimbo</div></div>');
  w.document.write('<div class="rodape">Documento gerado pelo sistema CAC GESTÃO.</div>');
  w.document.write('</body></html>');
  w.document.close();
  w.focus();
  setTimeout(()=>w.print(),300);
}

function App(){const[token,setToken]=useState(localStorage.getItem('token'));const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[dash,setDash]=useState(null);const[clientes,setClientes]=useState([]);const[show,setShow]=useState(false);const[detail,setDetail]=useState(null);const[form,setForm]=useState(empty);const[editing,setEditing]=useState(false);const[erro,setErro]=useState('');const[ok,setOk]=useState('');
const login=async e=>{e.preventDefault();setErro('');try{const r=await fetch(API+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error);localStorage.setItem('token',d.token);setToken(d.token)}catch(x){setErro(x.message)}};
const load=async()=>{const h={Authorization:'Bearer '+token};const[a,b]=await Promise.all([fetch(API+'/api/dashboard',{headers:h}),fetch(API+'/api/clientes',{headers:h})]);if(a.status===401){localStorage.removeItem('token');setToken(null);return}setDash(await a.json());setClientes(await b.json())};
useEffect(()=>{if(token)load()},[token]);
const save=async e=>{e.preventDefault();setErro('');setOk('');const r=await fetch(API+(editing?'/api/clientes/'+form.id:'/api/clientes'),{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setErro(d.error||'Não foi possível salvar');return}setOk(editing?'Cliente atualizado com sucesso.':'Cliente cadastrado com sucesso.');setForm(empty);setEditing(false);await load();setTimeout(()=>setShow(false),700)};
if(!token)return <main className="login"><section><h1>CAC GESTÃO</h1><p>Controle e gestão de clientes</p><form onSubmit={login}><input placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button>Entrar</button>{erro&&<small>{erro}</small>}</form></section></main>;
return <main><header><div><h1>CAC GESTÃO</h1><p>Controle e gestão de clientes</p></div><button className="secondary" onClick={()=>{localStorage.removeItem('token');setToken(null)}}>Sair</button></header>
<div className="toolbar"><h2>Dashboard</h2><button onClick={()=>{setErro('');setOk('');setEditing(false);setForm(empty);setShow(true)}}>+ Novo cliente</button></div>
<div className="cards">{dash&&Object.entries(dash).map(([k,v])=><article key={k}><b>{v}</b><span>{k}</span></article>)}</div>
<section className="panel"><div className="panelhead"><h2>Clientes cadastrados</h2><span>{clientes.length} registro(s)</span></div>{clientes.map(c=><div className="row" key={c.id}><div><button className="nameButton" onClick={async()=>{setErro('');try{const r=await fetch(API+'/api/clientes/'+c.id,{headers:{Authorization:'Bearer '+token}});const d=await r.json();if(r.ok)setDetail(d);else setErro(d.error||'Erro ao consultar cliente')}catch(e){setErro('Erro ao consultar cliente')}}}>{c.nome_completo||c.nome||c.razao_social}</button><small>{c.cpf_cnpj||'Sem CPF/CNPJ'} · {c.cidade||'Cidade não informada'}</small></div><span>{c.categoria_cac||c.tipo_cliente||'—'}</span><span className={c.status==='ativo'?'active':''}>{c.status}</span></div>)}{!clientes.length&&<p>Nenhum cliente cadastrado.</p>}</section>
{detail&&<div className="overlay"><section className="modal detailModal"><div className="modalhead"><div><h2>{detail.nome_completo||detail.nome||detail.razao_social}</h2><p>Perfil do cliente</p></div><button className="close" onClick={()=>setDetail(null)}>×</button></div><div className="detailGrid">{[['Código',detail.codigo],['CPF/CNPJ',detail.cpf_cnpj],['Tipo',detail.tipo_cliente],['Status',detail.status],['Telefone',detail.telefone],['WhatsApp',detail.whatsapp],['E-mail',detail.email],['Endereço',[detail.endereco,detail.numero,detail.complemento].filter(Boolean).join(', ')],['Cidade',[detail.cidade,detail.estado].filter(Boolean).join(' - ')],['Categoria CAC',detail.categoria_cac],['Número do CR',detail.cr_numero],['Validade do CR',detail.cr_validade],['Situação do CR',detail.cr_situacao],['Órgão emissor',detail.cr_orgao],['Responsável',detail.responsavel],['Origem do cadastro',detail.origem_cadastro]].map(([l,v])=><div className="detailItem" key={l}><span>{l}</span><b>{v||'—'}</b></div>)}</div><div className="detailObs"><span>Observações</span><p>{detail.observacoes||'—'}</p></div><div className="actions"><button className="secondary" onClick={()=>setDetail(null)}>Fechar</button><button className="secondary" onClick={()=>gerarDeclaracao(detail)}>Gerar declaração</button><button onClick={()=>{setForm({...empty,...detail});setEditing(true);setDetail(null);setShow(true)}}>Editar cliente</button></div></section></div>}{show&&<div className="overlay"><section className="modal"><div className="modalhead"><div><h2>{editing?'Editar cliente':'Novo cliente'}</h2><p>Cadastro completo do cliente</p></div><button className="close" onClick={()=>{setShow(false);setEditing(false)}}>×</button></div><form onSubmit={save}>
<h3>1. Identificação</h3><div className="grid"><F label="Código" name="codigo" form={form} setForm={setForm}/><F label="Nome completo / Razão social" name="nome_completo" required form={form} setForm={setForm}/><F label="CPF/CNPJ" name="cpf_cnpj" required form={form} setForm={setForm}/><F label="Data de nascimento / fundação" name="nascimento" type="date" form={form} setForm={setForm}/><label><span>Tipo de cliente</span><select value={form.tipo_cliente} onChange={e=>setForm({...form,tipo_cliente:e.target.value})}><option>Pessoa Física</option><option>Pessoa Jurídica</option></select></label><label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="ativo">Ativo</option><option value="inativo">Inativo</option><option value="bloqueado">Bloqueado</option></select></label></div>
<h3>2. Contatos</h3><div className="grid"><F label="Telefone" name="telefone" form={form} setForm={setForm}/><F label="WhatsApp" name="whatsapp" form={form} setForm={setForm}/><F label="E-mail" name="email" form={form} setForm={setForm}/></div>
<h3>3. Endereço</h3><div className="grid"><F label="CEP" name="cep" form={form} setForm={setForm}/><F label="Endereço" name="endereco" form={form} setForm={setForm}/><F label="Número" name="numero" form={form} setForm={setForm}/><F label="Complemento" name="complemento" form={form} setForm={setForm}/><F label="Bairro" name="bairro" form={form} setForm={setForm}/><F label="Cidade" name="cidade" form={form} setForm={setForm}/><F label="Estado" name="estado" form={form} setForm={setForm}/></div>
<h3>4. Gestão do cadastro</h3><div className="grid"><F label="Origem do cadastro" name="origem_cadastro" form={form} setForm={setForm}/><F label="Responsável" name="responsavel" form={form} setForm={setForm}/></div>
<h3>5. Perfil CAC</h3><div className="grid"><F label="Categoria CAC" name="categoria_cac" form={form} setForm={setForm}/><F label="Número do CR" name="cr_numero" form={form} setForm={setForm}/><F label="Emissão do CR" name="cr_emissao" type="date" form={form} setForm={setForm}/><F label="Validade do CR" name="cr_validade" type="date" form={form} setForm={setForm}/><label><span>Situação do CR</span><select value={form.cr_situacao} onChange={e=>setForm({...form,cr_situacao:e.target.value})}><option value="">Selecione</option><option>Regular</option><option>Próximo do vencimento</option><option>Vencido</option><option>Em análise</option></select></label><F label="Órgão emissor" name="cr_orgao" form={form} setForm={setForm}/></div>
<h3>6. Observações</h3><textarea rows="4" value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})} placeholder="Informações relevantes sobre o cliente..."/>
{erro&&<div className="msg error">{erro}</div>}{ok&&<div className="msg success">{ok}</div>}<div className="actions"><button type="button" className="secondary" onClick={()=>{setShow(false);setEditing(false)}}>Cancelar</button><button type="submit">{editing?'Salvar alterações':'Salvar cliente'}</button></div></form></section></div>}</main>}
createRoot(document.getElementById('root')).render(<App/>);